const OFFICIAL_REFERENCE = {
  title: "Greener Bangkok Community Waste Guide",
  url: "https://greener.bangkok.go.th/en/waste-recycle/community-waste-guide/",
  note:
    "Uses Bangkok's No-Mix Waste framing: food/organic, recyclable, general, and hazardous waste streams.",
};

const THAI_WASTE_RULES = {
  green: {
    bin: "green",
    uiColor: "green",
    binColor: "Green",
    label: "Green bin · Food / Organic waste",
    category: "food_organic",
    categoryDetail: "Food waste and organic waste",
    thaiName: "ขยะเศษอาหาร / ขยะอินทรีย์",
    chineseName: "厨余 / 有机垃圾",
    officialBasis:
      "Bangkok guidance separates food waste for the green stream, composting, animal feed, fertilizer, or other organic recovery.",
    examples: [
      "leftover food",
      "rice and noodles",
      "fruit peels",
      "vegetable scraps",
      "leaves and flowers",
      "eggshells",
    ],
    disposal:
      "Remove packaging first. Drain liquids where possible, then put food scraps and plant matter into the green organic stream or composting/animal-feed collection.",
    avoid:
      "Do not mix plastic bags, foam boxes, bottles, cans, batteries, bulbs, chemicals, or medicine with food waste.",
    thailandTips: [
      "Separate food waste at the source so it can be used for compost, fertilizer, animal feed, or other organic treatment.",
      "If the food is inside plastic, foam, or foil packaging, separate the packaging before disposal.",
    ],
    keywords: {
      en: [
        "food",
        "leftover",
        "leftovers",
        "rice",
        "noodle",
        "noodles",
        "meal",
        "fruit",
        "banana",
        "apple",
        "orange peel",
        "peel",
        "vegetable",
        "vegetables",
        "leaf",
        "leaves",
        "flower",
        "flowers",
        "eggshell",
        "egg shell",
        "compost",
        "organic",
        "wet waste",
        "garden waste",
        "meat scraps",
        "fish bone",
        "bones",
      ],
      th: ["อาหาร", "เศษอาหาร", "ขยะเปียก", "อินทรีย์", "ผลไม้", "เปลือก", "ผัก", "ใบไม้", "ดอกไม้"],
      zh: ["厨余", "有机", "剩饭", "剩菜", "果皮", "香蕉皮", "菜叶", "树叶", "花", "蛋壳", "湿垃圾"],
    },
  },
  yellow: {
    bin: "yellow",
    uiColor: "yellow",
    binColor: "Yellow",
    label: "Yellow bin · Recyclable waste",
    category: "recyclable",
    categoryDetail: "Clean recyclable waste",
    thaiName: "ขยะรีไซเคิล",
    chineseName: "可回收物",
    officialBasis:
      "Bangkok guidance separates recyclable items such as plastic bottles, paper, metal, and glass for collection points or recycling streams.",
    examples: [
      "plastic bottles",
      "glass bottles",
      "clean paper",
      "cardboard",
      "metal cans",
      "cartons",
    ],
    disposal:
      "Empty, rinse, and dry recyclable items. Flatten boxes and bottles when practical, then place them in the recyclable stream or take them to a collection point.",
    avoid:
      "Do not put oily, wet, or heavily food-contaminated packaging into recycling unless it can be cleaned first.",
    thailandTips: [
      "Clean and dry recyclables are more likely to be accepted and recovered.",
      "Food-stained foam boxes, dirty wrappers, and mixed-material packaging normally belong in general waste.",
    ],
    keywords: {
      en: [
        "recycle",
        "recyclable",
        "plastic bottle",
        "water bottle",
        "pet bottle",
        "bottle",
        "glass bottle",
        "glass jar",
        "jar",
        "paper",
        "newspaper",
        "magazine",
        "cardboard",
        "carton",
        "box",
        "metal can",
        "aluminium can",
        "aluminum can",
        "tin can",
        "soda can",
        "can",
        "milk carton",
        "tetra pak",
      ],
      th: ["รีไซเคิล", "ขวด", "ขวดพลาสติก", "ขวดแก้ว", "กระดาษ", "กล่อง", "กระป๋อง", "โลหะ"],
      zh: ["可回收", "回收", "塑料瓶", "瓶子", "玻璃瓶", "纸", "纸箱", "纸盒", "易拉罐", "金属罐"],
    },
  },
  blue: {
    bin: "blue",
    uiColor: "blue",
    binColor: "Blue",
    label: "Blue bin · General waste",
    category: "general",
    categoryDetail: "Non-recyclable, non-hazardous general waste",
    thaiName: "ขยะทั่วไป",
    chineseName: "一般垃圾",
    officialBasis:
      "Bangkok guidance treats snack bags, plastic bags, and non-recyclable mixed waste as general waste for the blue stream.",
    examples: [
      "snack bags",
      "plastic bags",
      "dirty wrappers",
      "foam containers",
      "tissues",
      "masks and diapers",
    ],
    disposal:
      "Bag securely and place in the blue general-waste stream. Separate any food, recyclable, or hazardous part before disposal when possible.",
    avoid:
      "General waste should not contain batteries, bulbs, chemicals, medicine, clean recyclables, or food scraps that can be separated.",
    thailandTips: [
      "Use general waste as the fallback only after separating food waste, clean recyclables, and hazardous waste.",
      "Wrap sharp broken ceramics or glass fragments before disposal for collection safety.",
    ],
    keywords: {
      en: [
        "general",
        "trash",
        "garbage",
        "mixed waste",
        "snack bag",
        "snack wrapper",
        "wrapper",
        "plastic bag",
        "bag",
        "foam",
        "styrofoam",
        "tissue",
        "napkin",
        "diaper",
        "mask",
        "ceramic",
        "porcelain",
        "dirty packaging",
        "food stained",
        "contaminated",
        "rubber",
        "cigarette",
      ],
      th: ["ทั่วไป", "ถุงขนม", "ซองขนม", "ถุงพลาสติก", "โฟม", "ทิชชู่", "หน้ากาก", "ผ้าอ้อม"],
      zh: ["一般垃圾", "其他垃圾", "塑料袋", "包装袋", "零食袋", "纸巾", "泡沫", "口罩", "尿布", "污染包装"],
    },
  },
  red: {
    bin: "red",
    uiColor: "red",
    binColor: "Orange / Red",
    label: "Orange / Red bin · Hazardous waste",
    category: "hazardous",
    categoryDetail: "Household hazardous waste",
    thaiName: "ขยะอันตราย",
    chineseName: "有害垃圾",
    officialBasis:
      "Bangkok guidance separates hazardous items such as batteries and light bulbs into the hazardous stream or community hazardous-waste collection.",
    examples: [
      "batteries",
      "light bulbs",
      "fluorescent lamps",
      "chemicals",
      "paint and aerosols",
      "medicine and e-waste",
    ],
    disposal:
      "Keep hazardous items sealed and separate. Use the hazardous-waste bin or a community/municipal hazardous collection point; never mix them with food, recycling, or general waste.",
    avoid:
      "Do not crush, open, burn, or mix leaking hazardous items with ordinary household waste.",
    thailandTips: [
      "Store leaking, broken, or sharp hazardous items in a protective container before drop-off.",
      "Batteries, bulbs, chemicals, medicine, and small electronics should be handled separately even when they are small.",
    ],
    keywords: {
      en: [
        "hazard",
        "hazardous",
        "toxic",
        "battery",
        "batteries",
        "power bank",
        "light bulb",
        "bulb",
        "fluorescent",
        "lamp",
        "chemical",
        "paint",
        "spray",
        "aerosol",
        "pesticide",
        "insecticide",
        "medicine",
        "medical",
        "syringe",
        "needle",
        "sharp",
        "e-waste",
        "ewaste",
        "electronic",
        "electronics",
        "phone",
        "charger",
        "circuit",
        "printer cartridge",
        "cartridge",
      ],
      th: ["อันตราย", "แบตเตอรี่", "ถ่านไฟฉาย", "หลอดไฟ", "สารเคมี", "ยา", "เข็ม", "อิเล็กทรอนิกส์"],
      zh: ["有害", "电池", "充电宝", "灯泡", "荧光灯", "化学", "油漆", "喷雾", "药品", "针头", "电子垃圾"],
    },
  },
};

const CATEGORY_ORDER = ["red", "green", "yellow", "blue"];

module.exports = {
  CATEGORY_ORDER,
  OFFICIAL_REFERENCE,
  THAI_WASTE_RULES,
};
